	rIllegalWord = new Array(
		"ANUS", "ASSH0LE", "ASSHOLE", "B00B", "B0FF", "B0OB", "B1TCH", "BASTARD", "BITCH", "BL0WJ0B", "BL0WJOB", "BLOW JOB", "BLOWJ0B", "BLOWJOB", "BLTCH", "BO0B", "BOFF", "BOOB", "BUTT", "C0CK", "C0M", "CH1NK", "CHINK", "CHLNK", "COCK", "CUM", "CUNT", "D0UCH", "D1CK", "DAMN", "DI1D0", "DI1DO", "DICK", "DILD0", "DILDO", "DLCK", "DOUCHE", "FAG", "FUCK", "GAY", "H0RNY", "HORNY", "JACKASS", "KUNT", "MASTERBATE", "MASTURBATE", "N1GGAR", "N1GGER", "NIGGAR", "NIGGER", "NLGGAR", "NLGGER", "0RGASM", "ORGASM", "P0RN", "PEN1S", "PENIS", "PENLS", "PORN", "PUSSY", "QUEER", "RECTUM", "RETARD", "S1UT", "SH1T", "SHIT", "SHLT", "SKANK", "SLUT", "T1TTY", "TITTY", "TLTTY", "TURD", "TWAT", "VAG1NA", "VAGINA", "VAGLNA", "W0P", "WETBACK", "WH0RE", "WHORE", "WOP", "XXX", "AHOLE", "ASH0LE", "ASH0LES", "ASHOLES", "ASS", "ASSLICK", "ASSMONKEY", "ASSFACE", "ASSH0LE", "ASSH0LEZ", "ASSHOLZ", "ASSKISSER", "ASSWIPE", "AZZHOLE", "BASSTARD", "BASSTERD", "BASSTURD", "BASTERD", "BASTERDS", "BASTERDZ", "BASTURD", "BELLYWHACKER", "BIATCH", "BONER", "BUCKETCUNT", "BUFU", "BULLSHIT", "BULLSHIT", "BUNGHOLE", "C0CK", "C0CKS", "C0K", "CARPETMUNCHER", "CAWK", "CAWKS", "CHEESYASS", "CIRCLEJERK", "CLIT", "CLIT", "COOCH", "COOCHIE", "COOTER", "COX", "CRUSTYCROTCH", "CUNNILINGUS", "DIKE", "DILD0", "DILD0S", "DILLD0", "DILLD0S", "DILLDOE", "DIPSHIT", "DOGGIESTYLE", "DONG", "DUMBASS", "DUMBASS", "DYKE", "ENEMA", "FUCK", "FUCKER", "FAIG", "FAIGS", "FAK", "FATASS", "FATSO", "FAYG", "FLIPPINGTHEBIRD", "FRIGGIN", "FROMHELL", "FUDGEPACKER", "FUK", "FUKAH", "FUKEN", "FUKER", "FUKIN", "FUKK", "FUKKAH", "FUKKEN", "FUKKER", "FUKKIN", "FURBURGER", "G00K", "GAZONGAS", "GAZONGERS", "GOD", "GODDAM", "GODDAMMIT", "GONADS", "GOOK", "GUINNE", "GUTTERSLUTBITCHFROMHELL", "H00R", "H0AR", "H0M0", "H0M0", "H0RE", "H0RNY", "HARDON", "HO", "HOAR", "HOAR", "HOMO", "HONKER", "HONKEY", "HONKY", "HOOKER", "HOOR", "HOORE", "HRNY", "JACKOFF", "JACKINGOFF", "JACKOFF", "JAP", "JAPS", "JELLYFACTORY", "JERKOFF", "JESUS", "JESUSCHRIST", "JIGSAWPUZZLE", "JISIM", "JISS", "JIZM", "JIZZ", "KIKE", "KNOBZ", "KRAUT", "LESBIAN", "LESBO", "LESSY", "LEZZIAN", "LICKMYCUNT", "LIPSHITS", "LIPSHITZ", "MASSTERBAIT", "MASSTRBAIT", "MASSTRBATE", "MASTERBAITER", "MERDE", "MICK", "MIERDA", "MOTHAFUCKER", "MOTHAFUKER", "MOTHAFUKKAH", "MOTHAFUKKER", "MOTHERFUCKER", "MOTHERFUKAH", "MOTHERFUKER", "MOTHERFUKKAH", "MOTHERFUKKER", "MOTHERFUCKER", "MOTHERFUCKER", "MUFF", "MUTHAFUCKER", "MUTHAFUKAH", "MUTHAFUKER", "MUTHAFUKKAH", "MUTHAFUKKER", "MUTHERFUCKER", "N1GR", "NIGGA", "NIGUR", "NIIGER", "NIIGR", "ONEEYEDBASTARD", "ORAFIS", "ORGASIM", "ORGASUM", "ORIFACE", "ORIFICE", "ORIFISS", "P0RN", "PACKI", "PACKIE", "PACKY", "PAKI", "PAKIE", "PAKY", "PECKER", "PECKERHEAD", "PEEENUS", "PEEENUSSS", "PEENUS", "PEINUS", "PEN1S", "PENAS", "PENUS", "PENUUS", "PHUC", "PHUCK", "PHUK", "PHUKER", "PHUKKER", "PINKTACO", "PISSANT", "PISSOFF", "PISSED", "PISSEDOFF", "POLAC", "POLACK", "POLAK", "POOPOO", "POONANI", "POONTANG", "PR1C", "PR1CK", "PR1K", "PRICK", "PROSTITUTE", "PUNTANG", "PUSSE", "PUSSEE", "QUEFE", "QUIEF", "QWEERS", "QWEERZ", "QWEIR", "REAM", "RECKTUM", "REVERSI", "RUMPRANGER", "SCANK", "SCHLONG", "SCHLONG", "SCHMEKA", "SCREWING", "SCROG", "SEMEN", "SH!T", "SH1T", "SH1TER", "SH1TS", "SH1TTER", "SH1TZ", "SHEISTER", "SHLONG", "SHMEGMA", "SHOOTINGAWAD", "SHOOTINGAWADE", "SHUTUP", "SHYT", "SHYTE", "SHYTTY", "SHYTY", "SKANCK", "SLACKASS", "SMEGMA", "SNATCH", "SONOFABITCH", "SONOFAWHORE", "SONOFABITCH", "SPERM", "SPIC", "SUCK", "SUCKMYCOCK", "SUCKMYDICK", "SUCKES", "TARD", "TIT", "TIT", "TITS", "TRAMP", "TRIPLEDELIGHTS", "VA1JINA", "VAG1NA", "VAGIINA", "VAJ1NA", "VAJINA", "VERTICALTACO", "VITRATOR", "VULLVA", "VULVA", "W0P", "WANG", "WANKER", "WEATBACK", "WH00R", "WH0RE", "RATED"
	);

function ch_BadWord(tmpstr)
{
	var userGame;
	var ListArray = eval("rIllegalWord");

	var BadWord = new Array();
	BadWord = ListArray;

	for(var i=0;i<BadWord.length;i++)
	{
		tmpstr=tmpstr.replace(BadWord[i],str_repeat("♡",BadWord[i].length));
	}

	return tmpstr;
}


function str_repeat(tmpstr,tmpnum)
{
	var retstr="";
	for(var i=0;i<tmpnum;i++)
		retstr+=tmpstr;
	return retstr;
}




function GetIllegalList() {
	rIllegalWord = new Array(
		"ANUS", "ASSH0LE", "ASSHOLE", "B00B", "B0FF", "B0OB", "B1TCH", "BASTARD", "BITCH", "BL0WJ0B", "BL0WJOB", "BLOW JOB", "BLOWJ0B", "BLOWJOB", "BLTCH", "BO0B", "BOFF", "BOOB", "BUTT", "C0CK", "C0M", "CH1NK", "CHINK", "CHLNK", "COCK", "CUM", "CUNT", "D0UCH", "D1CK", "DAMN", "DI1D0", "DI1DO", "DICK", "DILD0", "DILDO", "DLCK", "DOUCHE", "FAG", "FUCK", "GAY", "H0RNY", "HORNY", "JACKASS", "KUNT", "MASTERBATE", "MASTURBATE", "N1GGAR", "N1GGER", "NIGGAR", "NIGGER", "NLGGAR", "NLGGER", "0RGASM", "ORGASM", "P0RN", "PEN1S", "PENIS", "PENLS", "PORN", "PUSSY", "QUEER", "RECTUM", "RETARD", "S1UT", "SH1T", "SHIT", "SHLT", "SKANK", "SLUT", "T1TTY", "TITTY", "TLTTY", "TURD", "TWAT", "VAG1NA", "VAGINA", "VAGLNA", "W0P", "WETBACK", "WH0RE", "WHORE", "WOP", "XXX", "AHOLE", "ASH0LE", "ASH0LES", "ASHOLES", "ASS", "ASSLICK", "ASSMONKEY", "ASSFACE", "ASSH0LE", "ASSH0LEZ", "ASSHOLZ", "ASSKISSER", "ASSWIPE", "AZZHOLE", "BASSTARD", "BASSTERD", "BASSTURD", "BASTERD", "BASTERDS", "BASTERDZ", "BASTURD", "BELLYWHACKER", "BIATCH", "BONER", "BUCKETCUNT", "BUFU", "BULLSHIT", "BULLSHIT", "BUNGHOLE", "C0CK", "C0CKS", "C0K", "CARPETMUNCHER", "CAWK", "CAWKS", "CHEESYASS", "CIRCLEJERK", "CLIT", "CLIT", "COOCH", "COOCHIE", "COOTER", "COX", "CRUSTYCROTCH", "CUNNILINGUS", "DIKE", "DILD0", "DILD0S", "DILLD0", "DILLD0S", "DILLDOE", "DIPSHIT", "DOGGIESTYLE", "DONG", "DUMBASS", "DUMBASS", "DYKE", "ENEMA", "FUCK", "FUCKER", "FAIG", "FAIGS", "FAK", "FATASS", "FATSO", "FAYG", "FLIPPINGTHEBIRD", "FRIGGIN", "FROMHELL", "FUDGEPACKER", "FUK", "FUKAH", "FUKEN", "FUKER", "FUKIN", "FUKK", "FUKKAH", "FUKKEN", "FUKKER", "FUKKIN", "FURBURGER", "G00K", "GAZONGAS", "GAZONGERS", "GOD", "GODDAM", "GODDAMMIT", "GONADS", "GOOK", "GUINNE", "GUTTERSLUTBITCHFROMHELL", "H00R", "H0AR", "H0M0", "H0M0", "H0RE", "H0RNY", "HARDON", "HO", "HOAR", "HOAR", "HOMO", "HONKER", "HONKEY", "HONKY", "HOOKER", "HOOR", "HOORE", "HRNY", "JACKOFF", "JACKINGOFF", "JACKOFF", "JAP", "JAPS", "JELLYFACTORY", "JERKOFF", "JESUS", "JESUSCHRIST", "JIGSAWPUZZLE", "JISIM", "JISS", "JIZM", "JIZZ", "KIKE", "KNOBZ", "KRAUT", "LESBIAN", "LESBO", "LESSY", "LEZZIAN", "LICKMYCUNT", "LIPSHITS", "LIPSHITZ", "MASSTERBAIT", "MASSTRBAIT", "MASSTRBATE", "MASTERBAITER", "MERDE", "MICK", "MIERDA", "MOTHAFUCKER", "MOTHAFUKER", "MOTHAFUKKAH", "MOTHAFUKKER", "MOTHERFUCKER", "MOTHERFUKAH", "MOTHERFUKER", "MOTHERFUKKAH", "MOTHERFUKKER", "MOTHERFUCKER", "MOTHERFUCKER", "MUFF", "MUTHAFUCKER", "MUTHAFUKAH", "MUTHAFUKER", "MUTHAFUKKAH", "MUTHAFUKKER", "MUTHERFUCKER", "N1GR", "NIGGA", "NIGUR", "NIIGER", "NIIGR", "ONEEYEDBASTARD", "ORAFIS", "ORGASIM", "ORGASUM", "ORIFACE", "ORIFICE", "ORIFISS", "P0RN", "PACKI", "PACKIE", "PACKY", "PAKI", "PAKIE", "PAKY", "PECKER", "PECKERHEAD", "PEEENUS", "PEEENUSSS", "PEENUS", "PEINUS", "PEN1S", "PENAS", "PENUS", "PENUUS", "PHUC", "PHUCK", "PHUK", "PHUKER", "PHUKKER", "PINKTACO", "PISSANT", "PISSOFF", "PISSED", "PISSEDOFF", "POLAC", "POLACK", "POLAK", "POOPOO", "POONANI", "POONTANG", "PR1C", "PR1CK", "PR1K", "PRICK", "PROSTITUTE", "PUNTANG", "PUSSE", "PUSSEE", "QUEFE", "QUIEF", "QWEERS", "QWEERZ", "QWEIR", "REAM", "RECKTUM", "REVERSI", "RUMPRANGER", "SCANK", "SCHLONG", "SCHLONG", "SCHMEKA", "SCREWING", "SCROG", "SEMEN", "SH!T", "SH1T", "SH1TER", "SH1TS", "SH1TTER", "SH1TZ", "SHEISTER", "SHLONG", "SHMEGMA", "SHOOTINGAWAD", "SHOOTINGAWADE", "SHUTUP", "SHYT", "SHYTE", "SHYTTY", "SHYTY", "SKANCK", "SLACKASS", "SMEGMA", "SNATCH", "SONOFABITCH", "SONOFAWHORE", "SONOFABITCH", "SPERM", "SPIC", "SUCK", "SUCKMYCOCK", "SUCKMYDICK", "SUCKES", "TARD", "TIT", "TIT", "TITS", "TRAMP", "TRIPLEDELIGHTS", "VA1JINA", "VAG1NA", "VAGIINA", "VAJ1NA", "VAJINA", "VERTICALTACO", "VITRATOR", "VULLVA", "VULVA", "W0P", "WANG", "WANKER", "WEATBACK", "WH00R", "WH0RE", "RATED"
	);
	return rIllegalWord;
}

function DetectIllegalWord(sText) {
	rIllegalWord = GetIllegalList();
	SIZE = rIllegalWord.length;

	//sText = document.form.f1.value;
	for(i=0; i<SIZE; i++) {
		if(sText.indexOf(rIllegalWord[i]) != -1) {
			return 1;
		}
	}

}
